import { theImages } from "../../utils/imagesImport";

export const rentCardsData = [
  {
    id: 1, // Primary Key
    title: "Cozy Apartment in Downtown",
    location: "New York, USA",
    price: 120,
    currency: "USD",
    guests: 2,
    thumbnail: theImages["img01"],
    thumbnails: {
      img01_01: theImages["img01_01"],
      img01_02: theImages["img01_02"],
      img01_03: theImages["img01_03"],
      img01_04: theImages["img01_04"],
    },
    checkIn: "2024-11-10",
    checkOut: "2024-11-15",
    rate: 8.5,
    reviews: 58,
  },
  {
    id: 2,
    title: "Beachside Bungalow",
    location: "Malibu, USA",
    price: 250,
    currency: "USD",
    guests: 4,
    thumbnail: theImages["img02"],
    thumbnails: {
      img02_01: theImages["img02_01"],
      img02_02: theImages["img02_02"],
      img02_03: theImages["img02_03"],
      img02_04: theImages["img02_04"],
    },
    checkIn: "2024-12-05",
    checkOut: "2024-12-12",
    rate: 9.1,
    reviews: 118,
  },
  {
    id: 3,
    title: "Luxury Villa with Pool",
    location: "Santorini, Greece",
    price: 500,
    currency: "EUR",
    guests: 6,
    thumbnail: theImages["img03"],
    thumbnails: {
      img03_01: theImages["img03_01"],
      img03_02: theImages["img03_02"],
      img03_03: theImages["img03_03"],
      img03_04: theImages["img03_04"],
    },
    checkIn: "2024-11-18",
    checkOut: "2024-11-25",
    rate: 9.8,
    reviews: 108,
  },
  {
    id: 4,
    title: "Mountain Cabin Retreat",
    location: "Aspen, USA",
    price: 200,
    currency: "USD",
    guests: 5,
    thumbnail: theImages["img04"],
    thumbnails: {
      img04_01: theImages["img04_01"],
      img04_02: theImages["img04_02"],
      img04_03: theImages["img04_03"],
      img04_04: theImages["img04_04"],
    },
    checkIn: "2025-01-15",
    checkOut: "2025-01-22",
    rate: 8.7,
    reviews: 241,
  },
  {
    id: 5,
    title: "City Loft with Skyline View",
    location: "Tokyo, Japan",
    price: 180,
    currency: "JPY",
    guests: 2,
    thumbnail: theImages["img05"],
    thumbnails: {
      img05_01: theImages["img05_01"],
      img05_02: theImages["img05_02"],
      img05_03: theImages["img05_03"],
      img05_04: theImages["img05_04"],
    },
    checkIn: "2024-11-25",
    checkOut: "2024-12-02",
    rate: 7.9,
    reviews: 712,
  },
  {
    id: 6,
    title: "Historical Cottage in Countryside",
    location: "Provence, France",
    price: 220,
    currency: "EUR",
    guests: 4,
    thumbnail: theImages["img06"],
    thumbnails: {
      img06_01: theImages["img06_01"],
      img06_02: theImages["img06_02"],
      img06_03: theImages["img06_03"],
      img06_04: theImages["img06_04"],
    },
    checkIn: "2024-12-20",
    checkOut: "2024-12-27",
    rate: 8.3,
    reviews: 319,
  },
  {
    id: 7,
    title: "Modern Studio Near Beach",
    location: "Barcelona, Spain",
    price: 150,
    currency: "EUR",
    guests: 2,
    thumbnail: theImages["img07"],
    thumbnails: {
      img07_01: theImages["img07_01"],
      img07_02: theImages["img07_02"],
      img07_03: theImages["img07_03"],
      img07_04: theImages["img07_04"],
    },
    checkIn: "2024-11-30",
    checkOut: "2024-12-05",
    rate: 8.9,
    reviews: 1012,
  },
  {
    id: 8,
    title: "Rustic Farmhouse",
    location: "Tuscany, Italy",
    price: 300,
    currency: "EUR",
    guests: 6,
    thumbnail: theImages["img08"],
    thumbnails: {
      img08_01: theImages["img08_01"],
      img08_02: theImages["img08_02"],
      img08_03: theImages["img08_03"],
      img08_04: theImages["img08_04"],
    },
    checkIn: "2025-01-05",
    checkOut: "2025-01-12",
    rate: 9.4,
    reviews: 542,
  },
  {
    id: 9,
    title: "Urban Apartment in City Center",
    location: "Berlin, Germany",
    price: 160,
    currency: "EUR",
    guests: 3,
    thumbnail: theImages["img09"],
    thumbnails: {
      img09_01: theImages["img09_01"],
      img09_02: theImages["img09_02"],
      img09_03: theImages["img09_03"],
      img09_04: theImages["img09_04"],
    },
    checkIn: "2024-12-10",
    checkOut: "2024-12-17",
    rate: 8.0,
    reviews: 82,
  },
  {
    id: 10,
    title: "Lakefront Cabin",
    location: "Banff, Canada",
    price: 280,
    currency: "CAD",
    guests: 4,
    thumbnail: theImages["img10"],
    thumbnails: {
      img10_01: theImages["img10_01"],
      img10_02: theImages["img10_02"],
      img10_03: theImages["img10_03"],
      img10_04: theImages["img10_04"],
    },
    checkIn: "2024-12-25",
    checkOut: "2024-12-30",
    rate: 9.2,
    reviews: 27,
  },
];

// "Coastal Haven",
// "Mountain Retreat",
// "Ocean Breeze Villa",
// "Sunset Ridge",
// "Pinecone Chalet",
// "Whispering Pines Cabin",
// "Lakeside Serenity",
// "Seaside Escape",
// "Woodland Wanderer",
// "Horizon Hideaway",
// "Sandy Shores",
// "Tranquil Tides",
// "Alpine Getaway",
// "Rustic Roost",
// "Desert Oasis",
// "Meadowview Lodge",
// "Bluebird Cottage",
// "Twilight Haven",
// "Creekside Comfort",
// "Starlit Sanctuary",
// "Golden Dunes",
// "Hilltop Haven",
// "Emerald Isle",
// "Cozy Nook",
// "Sunny Side Retreat",
// "Maplewood Manor",
// "Crystal Cove",
// "Birchwood Bliss",
// "Velvet Horizon",
// "Shady Grove Cabin",
// "Harbor Hideaway",
// "Echo Valley Lodge",
// "Dreamcatcher Cabin",
// "Moonrise Manor",
// "Coastal Cove",
// "Mountain Majesty",
// "Skylark Suite",
// "Riverbend Retreat",
// "Pebble Path Cottage",
// "Cloud Nine Chalet",
// "Aspen Ascent",
// "Paradise Point",
// "Breezy Bluff",
// "Amber Ridge",
// "Golden Sunset Villa",
// "Serene Summit",
// "Island Glow",
// "Forest Fern Cottage",
// "Beachcomber’s Nest",
// "Driftwood Dreamhouse",
// "Hidden Harbor",
// "Sunny Vista Retreat",
// "Misty Mountain Lodge",
// "Silver Birch Cabin",
// "Wildflower Meadow",
// "Cedarwood Escape",
// "Golden Horizon",
// "Starry Skies Chalet",
// "Oceanfront Oasis",
// "Lush Lagoon",
// "Summit Solace",
// "Coastal Bliss",
// "Aurora Retreat",
// "Eagle’s Nest",
// "Sunrise Sanctuary",
// "Fern Valley Cabin",
// "Dune Drift Retreat",
// "Crimson Cove",
// "Secluded Shores",
// "Rolling Hills Haven",
// "Crystal Lagoon",
// "Autumn Leaf Lodge",
// "Blue Horizon Retreat",
// "Stony Brook Cabin",
// "Hummingbird Hideaway",
// "Velvet Creek Villa",
// "Rocky Ridge Lodge",
// "Sunny Cove Cottage",
// "Forest Haven",
// "Tidepool Treasure",
// "Moonlit Meadow",
// "Coveview Cottage",
// "Whispering Dunes",
// "Sunbeam Chalet",
// "Golden Grove",
// "Cascade Escape",
// "Orchard Oasis",
// "Amber Cove Retreat",
// "Skyview Summit",
// "Pine Haven Cabin",
// "Desert Bloom Villa",
// "Maple Ridge Retreat",
// "Snowcap Chalet",
// "Willow Creek Cottage",
// "Island Serenity",
// "Harvest Moon Haven",
// "Bayside Breeze",
// "Hidden Falls Cabin",
// "Silver Dune Retreat",
// "Celestial Shore"
